C14S:
	
	g++ raytracer.cpp build/buildChapter14.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm

C14A:
	
	g++ raytracer.cpp build/buildChapter14_AA.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm


MVPS:
	
	g++ raytracer.cpp build/buildMvp.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm

MVPA:
	
	g++ raytracer.cpp build/buildMvp_AA.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm

HWS:
	
	g++ raytracer.cpp build/buildHelloWorld.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm

HWA:
	
	g++ raytracer.cpp build/buildHelloWorld_AA.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm


d:
	
	g++ raytracer.cpp build/buildHelloWorld.cpp cameras/*.cpp geometry/*.cpp materials/*.cpp samplers/*.cpp utilities/*.cpp world/*.cpp -Wall -O -o raytracer -g
	time ./raytracer
	
	
	code scene.ppm